FinanceControl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('expence/', include('expenses.urls', namespace='expenses')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('income/', include('incomes.urls', namespace='incomes')),
    path('', include('usersettings.urls', namespace='usersettings')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'authentication'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('validate-username/', csrf_exempt(views.UsernameValidationView.as_view()), name='validate_username'),
    path('validate-email/', csrf_exempt(views.EmailValidationView.as_view()), name='validate_email'),
    path('activate/<uidb64>/<token>', views.VerificationView.as_view(), name='activate'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('password-reset/', views.RequestPasswordResetView.as_view(), name='request-password-reset'),
    path('password-reset-confirm/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]

incomes/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'incomes'
urlpatterns = [
    path('', views.IncomeIndexView.as_view(), name='index'),
    path('add-income', views.AddIncomeView.as_view(), name='add_income'),
    path('delete-income/<int:pk>', views.DeleteIncomeView.as_view(), name='delete_income'),
    path('edit-income/<int:pk>', views.EditIncomeView.as_view(), name='edit_income'),
    path('search-income/', csrf_exempt(views.SearchIncomeView.as_view()), name='search_income'),
]

incomes/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User


class Incomes(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits=25)
    date = models.DateField(default=now)
    description = models.CharField(max_length=600, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    source = models.CharField(max_length=255)

    def __str__(self):
        return self.source

    class Meta:
        ordering = ('-date',)


class Source(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

incomes/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.core.paginator import Paginator
import json
from django.utils.timezone import now
from django.db.models import Q
from usersettings.models import UserSettings
from .models import Incomes, Source
from django.contrib.auth.mixins import LoginRequiredMixin


class IncomeIndexView(LoginRequiredMixin, View):
    login_url = '/authentication/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):
        incomes = Incomes.objects.filter(owner=request.user)
        paginator = Paginator(incomes, 3)
        page_number = request.GET.get('page')
        page_obj = Paginator.get_page(paginator, page_number)

        user_currency = None
        if UserSettings.objects.filter(user=request.user).exists():
            user_currency = UserSettings.objects.get(user=request.user).currency
        context = {
            'incomes': incomes,
            'currency': user_currency,
            'page_obj': page_obj
        }

        return render(request, 'incomes/index.html', context)


class AddIncomeView(LoginRequiredMixin, View):
    login_url = '/authentication/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):
        sources = Source.objects.all()
        context = {
            'sources': sources,
        }
        return render(request, 'incomes/add_income.html', context)

    def post(self, request, *args, **kwargs):
        sources = Source.objects.all()
        amount = request.POST['amount']
        description = request.POST['description']
        source = request.POST['source']
        date = request.POST['income_date']
        user_currency = None
        if UserSettings.objects.filter(user=request.user).exists():
            user_currency = UserSettings.objects.get(user=request.user).currency
        context = {
            'sources': sources,
            'values': request.POST,
            'currency': user_currency
        }

        if not date:
            date = now()

        if not amount:
            messages.error(request, 'Amount must be added')
            return render(request, 'incomes/add_income.html', context)

        Incomes.objects.create(
            owner=request.user,
            amount=amount,
            description=description,
            source=source,
            date=date)
        if user_currency:
            messages.success(request, f'Income for {user_currency[:4]}{amount} has been added')
        else:
            messages.success(request, f'Income for {amount} has been added')
        return redirect('incomes:index')


class DeleteIncomeView(LoginRequiredMixin, View):
    login_url = '/authentication/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request, pk, *args, **kwargs):
        income = Incomes.objects.get(id=pk, owner=request.user)
        income.delete()
        messages.success(request, 'Income has been deleted')
        return redirect('incomes:index')


class EditIncomeView(LoginRequiredMixin, View):
    login_url = '/authentication/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request, pk, *args, **kwargs):
        income = Incomes.objects.get(id=pk, owner=request.user)
        sources = Source.objects.all()

        context = {
            'income': income,
            'sources': sources
        }
        return render(request, 'incomes/edit_income.html', context)

    def post(self, request, pk, *args, **kwargs):
        income = Incomes.objects.get(id=pk, owner=request.user)
        sources = Source.objects.all()
        amount = request.POST['amount']
        description = request.POST['description']
        source = request.POST['source']
        date = request.POST['income_date']

        context = {
            'income': income,
            'sources': sources,

        }

        if not date:
            date = now()

        if not amount:
            income.amount = None
            messages.error(request, 'Amount must be added')
            return render(request, 'incomes/edit_income.html', context)

        income.owner = request.user
        income.amount = amount
        income.date = date
        income.source = source
        income.description = description

        income.save()

        messages.success(request, 'Income updated  successfully')
        return redirect('incomes:index')


class SearchIncomeView(View):
    def post(self, request, *args, **kwargs):
        search_srt = json.loads(request.body).get('searchText')  # searchText from js

        incomes = Incomes.objects.filter(
            Q(owner=request.user)
            & (Q(amount__istartswith=search_srt)
               | Q(date__istartswith=search_srt)
               | Q(description__icontains=search_srt)
               | Q(source__icontains=search_srt)
               )
        )
        data = incomes.values()

        return JsonResponse(list(data), safe=False)

templates/incomes/add_income.html
{% extends 'base.html' %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'incomes:index' %}">Expenses</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add Expenses</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
        <form action="{% url 'incomes:add_income' %}" method="post">
            {% csrf_token %}
            {% include 'messages.html' %}
            <div class="form-group">
                <label for="">Amount</label>
                <input
                        type="number"
                        class="form-control form-control-sm"
                        name="amount"
                        value="{{values.amount}}"
                />
            </div>
            <div class="form-group">
                <label for="">Description</label>
                <input
                        type="text"
                        class="form-control form-control-sm"
                        name="description"
                        value="{{values.description}}"
                />
            </div>
            <div class="form-group">
                <label for="">Source</label>
                <select name="source" id="" class="custom-select">
                    {% for source in sources %}
                    <option name="source" value="{{source.name}}">{{ source.name }}</option>
                    {% endfor %}

                </select>
            </div>
            <div class="form-group">
                <label for="">Date of expense</label>
                <input
                        type="date"
                        class="form-control form-control-sm"
                        name="income_date"
                />
            </div>
            <button type="submit" value="Submit" class="btn btn-outline-success btn-lg btn-block">Add income</button>
        </form>
        </div>
        <div class="col-md-3"></div>
    </div>
{% endblock %}

templates/incomes/edit_income.html
{% extends 'base.html' %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'incomes:index' %}">Incomes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add Income</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
        <form action="{% url 'incomes:edit_income'  income.pk%}" method="post">
            {% csrf_token %}
            {% include 'messages.html' %}
            <div class="form-group">
                <label for="">Amount</label>
                <input
                        type="number"
                        class="form-control form-control-sm"
                        name="amount"
                        value="{{income.amount}}"
                />
            </div>
            <div class="form-group">
                <label for="">Description</label>
                <input
                        type="text"
                        class="form-control form-control-sm"
                        name="description"
                        value="{{income.description}}"
                />
            </div>
            <div class="form-group">
                <label for="">Source</label>
                <select name="source" id="" class="custom-select">
                    {% for source in sources %}
                    <option name="source" value="{{source.name}}">{{ source.name }}</option>
                    {% endfor %}

                </select>
            </div>
            <div class="form-group">
                <label for="">Date of expense</label>
                <input
                        type="date"
                        class="form-control form-control-sm"
                        name="income_date"
                        value="{{ income.date|date:'Y-m-d' }}"
                />
            </div>
            <button type="submit" value="Submit" class="btn btn-outline-primary btn-lg btn-block">Edit income</button>

        </form>
        <a href="{% url 'incomes:delete_income' income.pk %}"><button type="button"  class="btn btn-outline-danger btn-lg btn-block">Delete</button></a>
        </div>
        <div class="col-md-3"></div>
    </div>
{% endblock %}

templates/incomes/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if not request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "authentication:login" %}';
    </script>
    {% endif %}

    <div class="row">
        <div class="col-md-12">
            <div class="nav-container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Expenses</li>
                    <li class="breadcrumb-item"><a href="{% url 'incomes:add_income' %}">Add income</a></li>
                </ol>
                <a href="{% url 'incomes:add_income' %}"><button class="btn btn-sm btn-primary add-expense-btn">Add income</button></a>
            </div>
            {% include 'messages.html' %}
        </div>
    </div>
    <div class="row">
{#      <div class="col-md-8"></div>#}
      <div class="col-md-12">

        <div class="form-group">
          <input type="text" class="form-control" id="searchField" placeholder="Search...">
        </div>
      </div>
    </div>

    <div class="row">
        <div class="col-md-12">
        {% if incomes %}
            <div class="app-table">
                <table class="table table-hover table-bordered">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col" style="width: 12.5%">Data</th>
                        <th scope="col" style="width: 12.5%">Amount {% if currency %}({{ currency|slice:3 }}){% endif %}</th>
                        <th scope="col" style="width: 20%">Category</th>
                        <th scope="col" style="width: 42.5%">Description</th>
                        <th scope="col" style="width: 12.5%">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for income in page_obj %}
                        <tr>
                            <td >{{ income.date }}</td>
                            <td>{{ income.amount }}</td>
                            <td>{{ income.source }}</td>
                            <td>
                                {% if income.description|length > 30 %}
                                    <p style="margin: 0px;">
                                        {{ income.description|slice:":50" }}<span id="dots">...</span>
                                        <span id="more">{{income.description|slice:"50:"}}</span>
                                        <button onclick="myFunction()" id="myBtn" class="read-more-btn">Read more</button>
                                    </p>
                                {% else %}
                                    {{ income.description }}
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'incomes:edit_income' income.pk %}"><button type="button" class="btn btn-primary btn-sm btn-outline-primary" style="width: 45%">
                                    <i class="far fa-edit"></i>
                                </button></a>
                                <a href="{% url 'incomes:delete_income' income.pk %}"><button type="button" data-toggle="modal" data-target="#deleteModal" class="btn btn-secondary btn-sm btn-outline-danger" style="width: 45%; margin-left: 6%;">
                                    <i class="fas fa-trash"></i>
                                </button></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>

                {% else %}
                    <h3>No incomes yet, start by adding an income</h3>
                {% endif %}
                </table>
            </div>
{#           SEARCH RESULT TABLE   #}
            <h3 class="no-results" style="display: none;">No results found...</h3>
            <div class="table-output" style="display: none;">
              <table class="table table-hover table-bordered">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col" style="width: 12.5%">Data</th>
                    <th scope="col" style="width: 12.5%">Amount ({{ currency|slice:4 }})</th>
                    <th scope="col" style="width: 20%">Category</th>
                    <th scope="col" style="width: 42.5%">Description</th>
                    <th scope="col" style="width: 12.5%">Action</th>
                  </tr>
                </thead>

                <tbody  class="table-body">
                </tbody>
              </table>
            </div>

            {% if incomes %}
            <div class="pagination-container">
            <div class="">
                Showing page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} total ({{ incomes.all.count }})
            </div>
            <ul class="pagination align-right float-right mr-auto">
              {% if page_obj.has_previous %}
                  <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
                  <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
              {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>
              {% if page_obj.has_next %}
                  <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                  <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages}} &raquo;</a></li>
              {% endif %}
            </ul>
            </div>
            {% endif %}
            </div>
        </div>
    </div>
    <script src="{% static 'js/searchIncomes.js' %}"></script>
{% endblock content %}