FinanceControl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('expence/', include('expenses.urls', namespace='expenses')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('income/', include('incomes.urls', namespace='incomes')),
    path('', include('usersettings.urls', namespace='usersettings')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'authentication'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('validate-username/', csrf_exempt(views.UsernameValidationView.as_view()), name='validate_username'),
    path('validate-email/', csrf_exempt(views.EmailValidationView.as_view()), name='validate_email'),
    path('activate/<uidb64>/<token>', views.VerificationView.as_view(), name='activate'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('password-reset/', views.RequestPasswordResetView.as_view(), name='request-password-reset'),
    path('password-reset-confirm/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]

incomes/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'incomes'
urlpatterns = [
    path('', views.IncomeIndexView.as_view(), name='index'),
    path('add-income', views.AddIncomeView.as_view(), name='add_income'),
    path('delete-income/<int:pk>', views.DeleteIncomeView.as_view(), name='delete_income'),
    path('edit-income/<int:pk>', views.EditIncomeView.as_view(), name='edit_income'),
    path('search-income/', csrf_exempt(views.SearchIncomeView.as_view()), name='search_income'),
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.contrib.auth import login
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
import json
from django.http import JsonResponse
from django.contrib import messages
from validate_email import validate_email
from .token import account_activation_token
from django.contrib import auth
from usersettings.models import UserSettings
from django.contrib.auth.tokens import default_token_generator


class UsernameValidationView(View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        username = data['username']
        if not str(username).isalnum():
            return JsonResponse({'username_error': 'Username should only contain alphanumeric characters'}, status=406)
        if User.objects.filter(username=username).exists():
            return JsonResponse({'username_error': 'Sorry username is already taken,choose another one '}, status=409)
        if 5 > len(username) >= 1:
            return JsonResponse({'username_error': 'Username has to be more then 5 characters'}, status=406)
        return JsonResponse({'username_valid': True})


class EmailValidationView(View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        email = data['email']
        if not validate_email(email):
            return JsonResponse({'email_error': 'Please enter a valid email'}, status=400)
        if User.objects.filter(email=str(email).lower()).exists():
            return JsonResponse({'email_error': 'Email already taken'}, status=400)
        return JsonResponse({'email_valid': True})


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'authentication/register.html')

    def post(self, request, *args, **kwargs):
        user = request.POST
        context = {
            'fieldValues': request.POST
        }
        if not User.objects.filter(username=user['username']):
            if not User.objects.filter(email=user['email'].lower()):

                if user['password'] and user['password2']:
                    if user['password'] == user['password2']:
                        if len(user['password']) < 6:
                            messages.error(request, 'Password must be at least 6 digits long')
                            return render(request, 'authentication/register.html', context)

                        if len(user['username']) < 5:
                            messages.error(request, 'Username must be at least 5 digits long')
                            return render(request, 'authentication/register.html', context)

                        new_user = User.objects.create_user(username=user['username'], email=user['email'], password=user['password'])
                        new_user.is_active = False
                        new_user.save()

                        UserSettings.objects.create(user=new_user)

                        current_site = get_current_site(request)
                        subject = 'Activate your Account'
                        message = render_to_string('authentication/account_activation_email.html', {
                            'user': new_user,
                            'domain': current_site.domain,
                            'uid': urlsafe_base64_encode(force_bytes(new_user.pk)),
                            'token': account_activation_token.make_token(new_user),
                        })
                        new_user.email_user(subject=subject, message=message)

                        messages.success(request, 'Account successfully created an email has been sent to your email address')
                        return render(request, 'authentication/register.html')
                    else:
                        messages.error(request, 'Passwords must be identical')
                        return render(request, 'authentication/register.html', context)
                else:
                    messages.error(request, 'Please fill all the fields')
                    return render(request, 'authentication/register.html', context)

        messages.error(request, 'Username or email is invalid')
        return render(request, 'authentication/register.html', context)


class VerificationView(View):
    def get(self, request, uidb64, token):
        try:
            id = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=id)

            if not account_activation_token.check_token(user, token):
                return redirect('login'+'?message='+'User already activated')

            if user.is_active:
                return redirect('expenses:index')
            user.is_active = True
            user.save()

            messages.success(request, 'Account activated successfully')
            return redirect('authentication:login')

        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        return redirect('expenses:index')


class LoginView(View):
    def get(self, request, *args, **kwargs):

        return render(request, 'authentication/login.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        context = {
            'username': username
        }

        if username and password:
            user = auth.authenticate(username=username, password=password)
            if user:
                if user.is_active:  # Maybe not needed 'if'
                    login(request, user)
                    messages.success(request, 'Welcome ' + user.username + '!')
                    return redirect('expenses:index')
            elif User.objects.filter(username=username).exists():
                messages.error(request, 'Account is not active,please check your email')
                return render(request, 'authentication/login.html', context)
            else:
                messages.error(request, 'Username or password is invalid, try again')
                return render(request, 'authentication/login.html', context)

        messages.error(request, 'Please fill all fields')
        return render(request, 'authentication/login.html', context)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        auth.logout(request)
        messages.success(request, 'You have been logged out')
        return redirect('authentication:login')


class ChangePasswordView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'authentication/change_password.html')

    def post(self, request, *args, **kwargs):
        password = request.POST['password']
        new_password1 = request.POST['new_password1']
        new_password2 = request.POST['new_password2']

        user = User.objects.get(id=request.user.id)
        print(user.password)
        if user.check_password(password):
            if new_password1 and new_password2:
                if new_password1 == new_password2:
                    if len(new_password1) < 6:
                        messages.error(request, 'Password must be at least 6 digits long')
                        return render(request, 'authentication/change_password.html')
                    if password == new_password1:
                        messages.error(request, 'New password must be different form the old password')
                        return render(request, 'authentication/change_password.html')
                    user.set_password(new_password1)
                    user.save()
                    login(request, user)
                    messages.success(request, 'Password has been changed')
                    return render(request, 'authentication/change_password.html')
                else:
                    messages.error(request, 'Passwords must be identical')
                    return render(request, 'authentication/change_password.html')
            else:
                messages.error(request, 'Please fill all the fields')
                return render(request, 'authentication/change_password.html')

        else:
            messages.error(request, 'Wrong password')
            return render(request, 'authentication/change_password.html')


class RequestPasswordResetView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'authentication/reset_password.html')

    def post(self, request, *args, **kwargs):
        email = request.POST['email']

        context = {
            'values': request.POST
        }
        if not validate_email(email):
            messages.error(request, 'Please enter a valid email')
            return render(request, 'authentication/reset_password.html', context)
        if not User.objects.filter(email=email).exists():
            messages.error(request, 'Account with this email does not exist')
            return render(request, 'authentication/reset_password.html', context)

        this_user = User.objects.get(email=email)
        print(this_user.username)

        current_site = get_current_site(request)
        subject = 'Reset password for FinanceControl.com'
        message = render_to_string('authentication/reset_password_email.html', {
            'user': this_user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(this_user.pk)),
            'token': default_token_generator.make_token(this_user),
        })
        this_user.email_user(subject=subject, message=message)
        messages.success(request, f'A link has been send to {email}')

        return render(request, 'authentication/reset_password.html')


class PasswordResetConfirmView(View):

templates/authentication/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/authentication/change_password.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    {% if not request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "authentication:login" %}';
    </script>
    {% endif %}

    <div class="row">
    <div class="col-md-3">
    </div>
        <div class="col-md-6">
            <form action="{% url 'authentication:change_password' %}" method="post">
                {% csrf_token %}
                {% include 'messages.html' %}
                <div class="form-group">
                    <label for="">Old password</label>
                    <input
                            type="password"
                            class="form-control form-control-sm"
                            name="password"
                            value=""
                    />
                </div>
                <div class="form-group">
                    <label for="">New password</label>
                    <input
                            type="password"
                            class="form-control form-control-sm"
                            name="new_password1"
                            value=""
                    />
                </div>
                <div class="form-group">
                    <label for="">Repeat new password</label>
                    <input
                            type="password"
                            class="form-control form-control-sm"
                            name="new_password2"
                            value=""
                    />
                </div>
                <button type="submit" value="Submit" class="btn btn-outline-success btn-lg btn-block">Change password</button>
            </form>
        </div>
    <div class="col-md-3">
    </div>
    </div>



{% endblock content %}

templates/authentication/login.html
{% extends 'base_auth.html' %}
{% load static %}
{% block content %}
    {% if request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "expenses:index" %}';
    </script>
    {% endif %}

<div class="login-form">
    <form action="{% url 'authentication:login' %}" method="post">
        <h2 class="text-center">Log in</h2>

        {% csrf_token %}
        {% include 'messages.html' %}

        <div class="form-group mb-3">
            <input
                    type="text"
                    class="form-control"
                    placeholder="Username"
                    id="usernameField"
                    required="required"
                    name="username"
                    value="{{ username }}"
            >
        </div>
        <div class="form-group mb-3">
            <input
                    type="password"
                    class="form-control"
                    placeholder="Password"
                    id="passwordField"
                    required="required"
                    name="password"
            >
        </div>
        <div class="d-grid gap-2">
            <button class="btn btn-primary submit-btn mb-3 btn-block" type="submit" value="Login">Login</button>
        </div>
        <div class="clearfix">
{#            <label class="float-left form-check-label"><input type="checkbox"> Remember me</label>#}
            <a href="{% url 'authentication:request-password-reset' %}" class="float-right">Forgot Password?</a>
        </div>
    </form>
    <p class="text-center"><a href="{% url 'authentication:register' %}">Create an Account</a></p>
</div>

{% endblock content %}

templates/authentication/register.html
{% extends 'base_auth.html' %}
{% load static %}


{% block content %}
    {% if request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "expenses:index" %}';
    </script>
    {% endif %}

    <div class="login-form">
        <form action="{% url 'authentication:register' %}" method="post">
        <h2 class="text-center">Register</h2>

        {% csrf_token %}
        {% include 'messages.html' %}

        <div class="form-group mb-3">
            <input
                    type="text"
                    name="username"
                    placeholder="username"
                    id="usernameField"
                    value="{{fieldValues.username}}"
                    class="form-control form-control-sm"
            />
        </div>
            <div class="usernameFeedBackArea invalid-feedback" style="display:none"></div>
            <p class="text-sm text-success usernameSuccessOutput"></p>
        <div class="form-group mb-3">
            <input
                    type="email"
                    name="email"
                    placeholder="Email"
                    class="form-control form-control-sm"
                    id="emailField"
                    value="{{fieldValues.email}}"
            />
        </div>
            <div class="emailFeedBackArea invalid-feedback" style="display:none"></div>
        <div class="form-group mb-3">
            <input
                    type="password"
                    name="password"
                    placeholder="Password"
                    class="form-control form-control-sm"
                    id="passwordField"
            />
            <small class="float-right py-3 showPassword" >SHOW</small><br>
        </div>
        <div class="form-group mb-3">
            <input
                    type="password"
                    name="password2"
                    placeholder="Repeat password"
                    class="form-control form-control-sm"
            />
        </div>
        <div class="d-grid gap-2">
            <button class="btn btn-primary submit-btn mb-3 btn-block" type="submit" value="Register">Register</button>
        </div>
        <div class="clearfix">
{#            <label class="float-left form-check-label"><input type="checkbox"> Remember me</label>#}
{#            <a href="#" class="float-right">Forgot Password?</a>#}
        </div>
    </form>
    <p class="text-center"><a href="{% url 'authentication:login' %}">Already have an account?</a></p>
    </div>



<script src="{% static 'js/register.js' %}"></script>

{% endblock content %}

templates/authentication/reset_password.html
{% extends 'base_auth.html' %}
{% load static %}


{% block content %}
    {% if request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "expenses:index" %}';
    </script>
    {% endif %}

<div class="login-form">
    <form action="{% url 'authentication:request-password-reset' %}" method="post">
        <h2 class="text-center">Please enter your email address</h2>

        {% csrf_token %}
        {% include 'messages.html' %}

        <div class="form-group mb-3">
            <input
                    type="email"
                    class="form-control"
                    placeholder="Email"
                    required="required"
                    name="email"
                    value="{{ values.email }}"
            >
        </div>
        <div class="d-grid gap-2">
            <button class="btn btn-primary submit-btn mb-3 btn-block" type="submit" value="Submit">Reset Password</button>
        </div>
        <div class="clearfix">
        </div>
    </form>
    <p class="text-center"><a href="{% url 'authentication:register' %}">Create an Account</a></p>
    <p class="text-center"><a href="{% url 'authentication:login' %}">Login </a></p>
</div>

{% endblock content %}

templates/authentication/reset_password_confirm.html
{% extends 'base_auth.html' %}
{% load static %}
{% block content %}
    {% if request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "expenses:index" %}';
    </script>
    {% endif %}

<div class="login-form">
    <form action="{% url 'authentication:password-reset-confirm' uidb64 token %}" method="post">
        <h2 class="text-center">Create new password</h2>

        {% csrf_token %}
        {% include 'messages.html' %}

        <div class="form-group mb-3">
            <input
                    type="password"
                    class="form-control"
                    placeholder="Password"
                    required="required"
                    name="password"
            >
        </div>
        <div class="form-group mb-3">
            <input
                    type="password"
                    class="form-control"
                    placeholder="Repeat password"
                    required="required"
                    name="password2"
            >
        </div>
        <div class="d-grid gap-2">
            <button class="btn btn-primary submit-btn mb-3 btn-block" type="submit" value="CreatePassword">Create</button>
        </div>
        <div class="clearfix">
        </div>
    </form>
</div>

{% endblock content %}

templates/authentication/reset_password_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to reset your password:

http://{{ domain }}{% url 'authentication:password-reset-confirm' uidb64=uid token=token %}
{% endautoescape %}