FinanceControl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('expence/', include('expenses.urls', namespace='expenses')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('income/', include('incomes.urls', namespace='incomes')),
    path('', include('usersettings.urls', namespace='usersettings')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'authentication'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('validate-username/', csrf_exempt(views.UsernameValidationView.as_view()), name='validate_username'),
    path('validate-email/', csrf_exempt(views.EmailValidationView.as_view()), name='validate_email'),
    path('activate/<uidb64>/<token>', views.VerificationView.as_view(), name='activate'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('password-reset/', views.RequestPasswordResetView.as_view(), name='request-password-reset'),
    path('password-reset-confirm/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]

incomes/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'incomes'
urlpatterns = [
    path('', views.IncomeIndexView.as_view(), name='index'),
    path('add-income', views.AddIncomeView.as_view(), name='add_income'),
    path('delete-income/<int:pk>', views.DeleteIncomeView.as_view(), name='delete_income'),
    path('edit-income/<int:pk>', views.EditIncomeView.as_view(), name='edit_income'),
    path('search-income/', csrf_exempt(views.SearchIncomeView.as_view()), name='search_income'),
]

usersettings/urls.py
from django.urls import path
from . import views


app_name = 'usersettings'
urlpatterns = [
    path('settings/', views.CurrencySettingsView.as_view(), name='settings'),
    path('account-settings/', views.AccountSettingView.as_view(), name='account_settings')
]

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>TrulyExpenses {% block title %} {% endblock %}</title>

    <!-- Font Awesome -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" />
    <link href="{% static 'css/main.css'%}" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet" />
  </head>
  <body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% url 'expenses:index' %}">Finance control</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

   <ul class="navbar-nav px-3" style="display: flex; flex-direction: row; align-items: center;">
       <li class="nav-item text-nowrap" style="margin-right: 30px;">
          <span class="nav-link" href="">
            Welcome, {{request.user.username}}
          </span>
        </li>
    <li class="nav-item text-nowrap" style="margin-right: 30px;">
      <a  class="nav-link" href="{% url 'authentication:logout' %}">Sign out</a>
    </li>
  </ul>
</header>

<div class="container-fluid">
  <div class="row">
        {#      SIDEBAR        #}
      {% include 'sidebar.html'  %}
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
     {% block content %}

     {% endblock content %}
    </main>
  </div>
</div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
     <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/base_auth.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>TrulyExpenses {% block title %} {% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" />
    <link href="{% static 'css/main.css'%}" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet" />
  </head>

  <body>
    <main class="col-md-12">
        {% block content %}

        {% endblock content %}
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script>
      window.jQuery ||
        document.write(
          '<script src="/docs/4.4/static/js/vendor/jquery.slim.min.js"><\/script>'
        );
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
     <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-sm alert-{{ message.tags }}"{% endif %}>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

templates/sidebar.html
{% load static %}
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'dashboard:index' %}">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'expenses:index' %}">Expenses</a>
            </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'incomes:index' %}">Income</a>
            </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Summary</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              Expenses summary
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              Income summary
            </a>
          </li>
        </ul>
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Settings</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'usersettings:settings' %}">
              General settings
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%  url 'usersettings:account_settings' %}">
              Account settings
            </a>
          </li>
        </ul>
      </div>
    </nav>