FinanceControl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('expence/', include('expenses.urls', namespace='expenses')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('income/', include('incomes.urls', namespace='incomes')),
    path('', include('usersettings.urls', namespace='usersettings')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'authentication'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('validate-username/', csrf_exempt(views.UsernameValidationView.as_view()), name='validate_username'),
    path('validate-email/', csrf_exempt(views.EmailValidationView.as_view()), name='validate_email'),
    path('activate/<uidb64>/<token>', views.VerificationView.as_view(), name='activate'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('password-reset/', views.RequestPasswordResetView.as_view(), name='request-password-reset'),
    path('password-reset-confirm/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]

dashboard/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search-dashboard/', csrf_exempt(views.SearchDashboardView.as_view()), name='search_dashboard'),
]

expenses/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'expenses'
urlpatterns = [
    path('', views.ExpenceIndexView.as_view(), name='index'),
    path('add-expense', views.AddExpenseView.as_view(), name='add_expense'),
    path('delete-expense/<int:pk>', views.DeleteExpenseView.as_view(), name='delete_expense'),
    path('edit-expense/<int:pk>', views.EditExpenseView.as_view(), name='edit_expense'),
    path('search-expenses/', csrf_exempt(views.SearchRequestView.as_view()), name='search_expenses'),
]

incomes/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'incomes'
urlpatterns = [
    path('', views.IncomeIndexView.as_view(), name='index'),
    path('add-income', views.AddIncomeView.as_view(), name='add_income'),
    path('delete-income/<int:pk>', views.DeleteIncomeView.as_view(), name='delete_income'),
    path('edit-income/<int:pk>', views.EditIncomeView.as_view(), name='edit_income'),
    path('search-income/', csrf_exempt(views.SearchIncomeView.as_view()), name='search_income'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
import json
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from expenses.models import Expense, Category
from incomes.models import Incomes, Source
from itertools import chain
from usersettings.models import UserSettings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(LoginRequiredMixin, View):
    login_url = '/authentication/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):
        expenses = Expense.objects.filter(owner=request.user)
        incomes = Incomes.objects.filter(owner=request.user)

        expenses_and_incomes = sorted(chain(expenses, incomes), key=lambda instance: instance.date, reverse=True)

        paginator = Paginator(list(expenses_and_incomes), 7)
        page_number = request.GET.get('page')
        page_obj = Paginator.get_page(paginator, page_number)

        user_currency = None
        if UserSettings.objects.filter(user=request.user).exists():
            user_currency = UserSettings.objects.get(user=request.user).currency

        context = {
            'all_obj': expenses_and_incomes,
            'currency': user_currency,
            'page_obj': page_obj
        }

        return render(request, 'dashboard/index.html', context)


class SearchDashboardView(View):
    def post(self, request, *args, **kwargs):
        search_srt = json.loads(request.body).get('searchText')  # searchText from js

        expenses = Expense.objects.filter(
            Q(owner=request.user)
            & (Q(amount__istartswith=search_srt)
               | Q(date__icontains=search_srt)
               | Q(description__icontains=search_srt)
               | Q(category__icontains=search_srt)
               )
        )
        incomes = Incomes.objects.filter(
            Q(owner=request.user)
            & (Q(amount__istartswith=search_srt)
               | Q(date__icontains=search_srt)
               | Q(description__icontains=search_srt)
               | Q(source__icontains=search_srt)
               )
        )
        data1 = expenses.values()
        data2 = incomes.values()

        return JsonResponse((list(data1), list(data2)), safe=False)

templates/dashboard/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if not request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "authentication:login" %}';
    </script>
    {% endif %}

    <div class="row">
        <div class="col-md-12">
            <div class="nav-container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                </ol>
            </div>
            {% include 'messages.html' %}
        </div>
    </div>
    <div class="row">
{#      <div class="col-md-8"></div>#}
      <div class="col-md-12">

        <div class="form-group">
          <input type="text" class="form-control" id="searchField" placeholder="Search...">
        </div>
      </div>
    </div>

    <div class="row">
        <div class="col-md-12">
        {% if all_obj %}
            <div class="app-table">
                <table class="table table-hover table-bordered">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col" style="width: 12.5%">Data</th>
                        <th scope="col" style="width: 12.5%">Amount {% if currency %}({{ currency|slice:3 }}){% endif %}</th>
                        <th scope="col" style="width: 20%">Category</th>
                        <th scope="col" style="width: 42.5%">Description</th>
                        <th scope="col" style="width: 12.5%">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in page_obj %}
                        {% if obj.source %}
                        <tr class="table-success">
                            <td>{{ obj.date }}</td>
                            <td>{{ obj.amount }}</td>
                            <td>{{ obj.source }}</td>
                            <td>
                                {% if obj.description|length > 30 %}
                                    <p style="margin: 0px;">
                                        {{ obj.description|slice:":50" }}<span id="dots">...</span>
                                        <span id="more">{{obj.description|slice:"50:"}}</span>
                                        <button onclick="myFunction()" id="myBtn" class="read-more-btn">Read more</button>
                                    </p>
                                {% else %}
                                    {{ obj.description }}
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'incomes:edit_income' obj.pk %}"><button type="button" class="btn btn-primary btn-sm btn-outline-primary" style="width: 45%">
                                    <i class="far fa-edit"></i>
                                </button></a>
                                <a href="{% url 'incomes:delete_income' obj.pk %}"><button type="button" data-toggle="modal" data-target="#deleteModal" class="btn btn-secondary btn-sm btn-outline-danger" style="width: 45%; margin-left: 6%;">
                                    <i class="fas fa-trash"></i>
                                </button></a>
                            </td>
                        </tr>
                            {% else %}
                        <tr class="table-danger">
                            <td>{{ obj.date }}</td>
                            <td>{{ obj.amount }}</td>
                            <td>{{ obj.category }}</td>
                            <td>
                                {% if obj.description|length > 30 %}
                                    <p style="margin: 0px;">
                                        {{ obj.description|slice:":50" }}<span id="dots">...</span>
                                        <span id="more">{{obj.description|slice:"50:"}}</span>
                                        <button onclick="myFunction()" id="myBtn" class="read-more-btn">Read more</button>
                                    </p>
                                {% else %}
                                    {{ obj.description }}
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'expenses:edit_expense' obj.pk %}"><button type="button" class="btn btn-primary btn-sm btn-outline-primary" style="width: 45%">
                                    <i class="far fa-edit"></i>
                                </button></a>
                                <a href="{% url 'expenses:delete_expense' obj.pk %}"><button type="button" data-toggle="modal" data-target="#deleteModal" class="btn btn-secondary btn-sm btn-outline-danger" style="width: 45%; margin-left: 6%;">
                                    <i class="fas fa-trash"></i>
                                </button></a>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>

                {% else %}
                    <h3>No incomes yet, start by adding an income</h3>
                {% endif %}
                </table>
            </div>
{#           SEARCH RESULT TABLE   #}
            <h3 class="no-results" style="display: none;">No results found...</h3>
            <div class="table-output" style="display: none;">
              <table class="table table-hover table-bordered">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col" style="width: 12.5%">Data</th>
                    <th scope="col" style="width: 12.5%">Amount ({{ currency|slice:4 }})</th>
                    <th scope="col" style="width: 20%">Category</th>
                    <th scope="col" style="width: 42.5%">Description</th>
                    <th scope="col" style="width: 12.5%">Action</th>
                  </tr>
                </thead>

                <tbody  class="table-body">
                </tbody>
              </table>
            </div>

            {% if all_obj %}
            <div class="pagination-container">
            <div class="">
                Showing page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </div>
            <ul class="pagination align-right float-right mr-auto">
              {% if page_obj.has_previous %}
                  <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
                  <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
              {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>
              {% if page_obj.has_next %}
                  <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                  <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages}} &raquo;</a></li>
              {% endif %}
            </ul>
            </div>
            {% endif %}
            </div>
        </div>
    </div>
    <script src="{% static 'js/searchDashboard.js' %}"></script>
{% endblock content %}